fix: cache earthly binary (self-made)

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -18,16 +18,37 @@ jobs:
       DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
       DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
       FORCE_COLOR: 1
+      earthly-version: v0.8.13
+      earthly-path: /tmp/earthly/${{ earthly-version }}
     permissions:
       contents: write
     steps:
     - uses: actions/checkout@v4
-    - name: Download and cache earthly binary
-      uses: supplypike/setup-bin@v4
+
+    - name: Setup cache for earthly binary
+      id: earthly-binary
+      uses: actions/cache@v2
       with:
-        uri: 'https://github.com/earthly/earthly/releases/download/v0.8.13/earthly-linux-amd64'
-        name: 'earthly'
-        version: '0.8.12'
+        path: ${{ earthly-path }}
+        key: earthly-${{ runner.os }}-${{ hashFiles('/tmp/earthly${{ earthly-version}}/earthly') }}
+
+    - name: Download Binary if Not Cached
+      if: steps.earthly-binary.outputs.cache-hit != 'true'
+      run: |
+        mkdir -p ${{ earthly-path }}
+        curl -L -o ${{ earthly-path }}/earthly https://github.com/earthly/earthly/releases/download/${{ earthly-version }}/earthly-linux-amd64
+        chmod +x ${{ earthly-path }}/earthly
+
+    - name: Add binary to PATH
+      run: echo "${{ earthly-path }}/earthly" >> $GITHUB_PATH
+
+    - name: Verify Binary Download and Cache
+      run: |
+        if [ -f "${{ earthly-path }}/earthly" ]; then
+          echo "Binary download and cache successful!"
+        else
+          echo "Binary download or cache failed!"
+          exit 1
         
     - name: Docker Login
       run: docker login --username "$DOCKERHUB_USERNAME" --password "$DOCKERHUB_TOKEN"
